name: Build Custom Android
on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4       # Updated to v4
      - uses: actions/setup-java@v4     # Updated to v4
        with:
          distribution: 'zulu'
          java-version: "17"            # Updated to 17 (better compatibility with newer Flutter)
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5"
          channel: 'stable'
          cache: true
          
      - name: Get dependencies
        run: flutter pub get

      - name: Generate App Icons
        run: dart run flutter_launcher_icons

      - name: Build Flutter (APK)
        run: flutter build apk --debug

      - uses: actions/upload-artifact@v4  # <--- THIS WAS THE ERROR (Fixed to v4)
        with:
          name: SimpleWoL-Custom
          path: build/app/outputs/flutter-apk/app-debug.apk
